{% set name = "pytest-doctestplus" %}
{% set version = "1.7.1" %}
{% set deselect_tests = "" %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/test_doctestplus.py::test_remote_data_all"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/test_doctestplus.py::test_remote_data_url"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/test_doctestplus.py::test_remote_data_float_cmp"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/test_doctestplus.py::test_remote_data_ignore_whitespace"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/test_doctestplus.py::test_remote_data_ellipsis"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/test_doctestplus.py::test_remote_data_requires"' %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/test_doctestplus.py::test_remote_data_ignore_warnings"' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 64ae16dbda66c3db775ef596828d8d7adda09c6f34dd85099c119e4ff8cfe5b6

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=30.3.0
    - setuptools_scm
    - wheel
    - setuptools-scm
  run:
    - python
    - pytest >=7.0
    - packaging >=17.0

test:
  source_files:
    - tests/
  imports:
    - pytest_doctestplus
  requires:
    - pip
    - pytest
    - setuptools >=30.3.0
    - numpy
  commands:
    - pip check
    - pytest -vv tests {{ deselect_tests }}

about:
  home: https://github.com/astropy/pytest-doctestplus
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Pytest plugin with advanced doctest features.
  description: |
    This package contains a plugin for the pytest framework that provides
    advanced doctest support and enables the testing of reStructuredText files.
  doc_url: https://github.com/astropy/pytest-doctestplus
  dev_url: https://github.com/astropy/pytest-doctestplus

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - pllim
    - mwcraig
