{% set name = "pytest-doctestplus" %}
{% set version = "0.3.0" %}
{% set git_url = "https://github.com/astropy/pytest-doctestplus" %}
{% set sha256 = "4e641bc720661c08ec3afe44a7951660cdff5e187259c433aa66e9ec2d5ccea1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - pytest >=3.0
    - six
  run:
    - python
    - pytest >=3.0
    - numpy >=1.10
    - six

test:
  imports:
    - pytest_doctestplus

about:
  home: {{ git_url }}
  license: BSD
  license_family: BSD 3-Clause
  license_file: LICENSE.rst
  summary: 'Pytest plugin with advanced doctest features'
  description: |
    This package contains a plugin for the pytest framework that provides
    advanced doctest support and enables the testing of reStructuredText files.
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - drdavella
    - mwcraig
