{% set name = "pytest-doctestplus" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 709ad23ea98da9a835ace0a4365c85371c376e000f2860f30de6df3a6f00728a

build:
  skip: True  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - wheel
  run:
    - python
    - pytest >=4.6
    - setuptools >=30.3.0
    - sphinx

test:
  imports:
    - pytest_doctestplus
  requires:
    - pip
    - python <3.10
  commands:
    - pip check

about:
  home: https://github.com/astropy/pytest-doctestplus
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Pytest plugin with advanced doctest features.
  description: |
    This package contains a plugin for the pytest framework that provides
    advanced doctest support and enables the testing of reStructuredText files.
  doc_url: https://github.com/astropy/pytest-doctestplus
  dev_url: https://github.com/astropy/pytest-doctestplus

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - pllim
    - mwcraig
