travis:
  secure:
    BINSTAR_TOKEN: rPA0csDwoj6nNZaC62rxBI9jKeXj7bIuJUPi+52OTW7ADcorjmvx/m4dKwbOZrNsHvscVvHt/H44KEpUMnZKSPZv/MoFnEDeLF6GKJkpwpDgMuZq44+SwM/xq+Gy1GlPxbXCFSzMscrby4HWrVcvrLKFoTSkiJo4U54J9YWTo3b+p2/kY/rOABD5znAhgQnpQOO6kbL+1ScYryhlM8Lk4a8uv4QCpmK/vIKxVPT6ATesaK2JxWrQWGQwmTY0QXnFkQ7Qo/we0KAvRpe15v9jFgQeO1U1sZ3RxGM/Kbo2q2uthx4OtJderHR37faXwzTc/2U5m5klIMFPa0NOswZ/DQBQYPT1dSu5Xzq6vkn6YLFQjDGKbQTQad0aZlpvRJ0Utq6KErCO9vhXDmiYT4AWqaoHeoHBas9xjfSTCZhahrJywbFA/p2Q68DqQjjHDDPUvMpzWtn5R2h+l143jECFOZHL4/x5dqwEfAuUJZEEmDaAk50cAykn+8FJrojrFHhT5grawf5AlZaB8xUFANHrg1oSgUpQJcP/kpDgCGlxy1ip7HP7r2BQBwwFujK+Kg/epaNDDuIxLWIjc4fAE1qjRIn6njGtODOF/4haCQi/NzsTVDOyfNhszXSFDZOPujHN1b+UDBBM6rY6jyCeHtsYCJQaBbzaMuUD/5raazEJ61A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
