travis:
  secure:
    BINSTAR_TOKEN: g0aasgUfHrrxXNUwDWlw9MgADLIahuwUohYHLgYJilal5eVT98IW5LMd5W5hE2FNZdq0GSY5NEVZXFtu0E/JMCJwOt3vEmWJ5vBseT6N1V0hR4+w8ZCOjB5peEZ90MmlvEeBjXdZ33ev7AefxwyO8/Eo7AEa1+mc+jveROr1iFYJc2v5QrrxSdAsoBDeYKcYI3FT9a9/0crcv409IEK7UhUNgaE2tmJ+aY3eAYttFvYgwlkGjnGMYxTluHBsJJ+uLdNd0Bb+R5yAsZBhBdERFFsGO8C7tgY8e+0JB5QWi43cj+lvCZMKkLM+ZVZP1YYElpPGzYf2lzC61xx4ShwnYsM8zB1K3nAdV/xD6NJu4DHFntdt71dV5d9xVT8xZns8qJ5YwPVwIHYp9aBp1yJVrZlzhvDE9DXLk2XSLz/3wYgcH5H0/4s/bAM8HDM+tsLTI7+awqxPPI3S+HhKmVMpOeohEcW4A/QJTHXhk5MLzfJsRxrCQS0NkbdNx6A/J4593oayeS1/WBWJg0w1KRF1cCrR+FFX7MAJFKUcfqXLKapyxzviVFikW/jJOxHcVgFxE7qhe417N+iwbQAD97QHnBbhpjzwzILTSD+OrvwkekSMpjxCxXuGa+sbla3BtF9aN+XvNCIJvf5h59MFLGyNgLvqElALf+p336D8C1KwpJg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
