travis:
  secure:
    BINSTAR_TOKEN: vABmUE3XLlyEA/gg66f3av025wfzpoI/Z0AkWvySLBGsFOkdykjLYyM0aga6VCdOf5zCIb16o91R/OZ5kuFkY9tKZ/QnAWaXifJIo5hTxq5TZEg76FviUbPd+mQ9V+obrSiZ0cXnS5ihohALPBcHMqKHUG13YhIJGvQYmXYifOFBkAaS/slqFNJZmTG4+5B3qcReveI6zUSPIjpSktYrsZnWCxa2nSviio3g6+pX8JFENm3jZzscEHNS9dNJDm/cR0qLcs6oHXqKIt5pvrB7O0efQvJ9LoO5IikxW95T8CPybMpRP+BsGgRKpirdMedysjACSpcCn4fG0QccfgOgI1swutk3TnrggMCEktNhnpU+ep6wBghKzSq2fh2gD7Pv5tE/zGqC+iJMf1Axc6bG55DwKNu5CuFuWuFYKQqLJBJVgLKV2kNV8ENMA7GBzpUVku5FUyThi1UltY92G/9qnnASNjPuPd93s0OXfdg2mkNOkMXS+6q5KB3Aaggs/3qd6T6euEtf1Jw8BOvePP1voPD7BWjlAQjb3bvWpERTeW6th/ZoEg8cS7U2JXHQtdoeuEdvTtj+ol3gmGvAqci3iFQNZ+HaRBXwL1EH4SOEO1gm84cPG0m5uD3pQyaMvouRYU4nIpFXIWoohrR6IAeezBLPafMNQu5WgzrpVVvZ0+I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
